name: Build Kernel

on:
  push:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Setup Timezone
        uses: szenius/set-timezone@master
        with:
          timezoneLinux: "Asia/Makassar"

      - name: Setup rwMem Driver
        run: |
          cd drivers
          wget https://filebin.net/uj8f6h73t97ekprq/rwMem.zip
          unzip rwMem.zip
          cd rwMem/rwMem
          make CC=clang LLVM=1 KDIR=/home/runner/work/surya_kernel_x3/surya_kernel_x3/out

      - name: Set rwMem Module Path
        run: |
          MODULE_PATH="/home/runner/work/surya_kernel_x3/surya_kernel_x3/out/drivers/rwMem/rwMem.ko"
          echo "MODULE_PATH=$MODULE_PATH" >> $GITHUB_ENV

      - name: Run Non-KSU Build Script
        run: |
          export KBUILD_BUILD_USER=g4hmx
          export KBUILD_BUILD_HOST=pocox3
          source build.sh
          echo "ZIPNAME=${ZIPNAME}" >> $GITHUB_ENV

      - name: Run KernelSU-Next Build Script
        run: |
          export KBUILD_BUILD_USER=g4hmx
          export KBUILD_BUILD_HOST=pocox3
          source build.sh --su
          echo "ZIPNAME_KSU=${ZIPNAME_KSU}" >> $GITHUB_ENV

      - name: Upload Non-KSU Artifact
        uses: actions/upload-artifact@main
        with:
          name: Non-KSU-Artifact
          path: ${{ env.ZIPNAME }}

      - name: Upload KernelSU-Next Artifact
        uses: actions/upload-artifact@main
        with:
          name: KSUNext-Artifact
          path: ${{ env.ZIPNAME_KSU }}

      - name: Upload rwMem Kernel Module
        uses: actions/upload-artifact@main
        with:
          name: rwMem-Kernel-Module
          path: ${{ env.MODULE_PATH }}
